In [73]:
import numpy as np
import pandas as pd
from keras.layers import Dense
from keras.models import Sequential
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import scale
from sklearn.model_selection import train_test_split

Traffic_Data = pd.read_csv('/Users/MattPettit/Desktop/Metro_Interstate_Traffic_Volume.csv')
Traffic_DF = pd.DataFrame(Traffic_Data)
Traffic_DF = Traffic_DF.drop(columns=['date_time'])
Traffic_DF_X = Traffic_DF.iloc[:,0:5]
Traffic_DF_Y = Traffic_DF.iloc[:,5]

traff_scale = scale(Traffic_DF_X)
traff_scale_DF = pd.DataFrame(traff_scale)

#Train_test_split
x = traff_scale_DF
y = Traffic_DF_Y
x_train, x_test, y_train, y_test = train_test_split(x, y, train_size=.7)
n_cols = x_train.shape[1]

#Model build
traff_model = Sequential()
traff_model.add(Dense(100, activation='relu', input_shape=(n_cols,)))
traff_model.add(Dense(100, activation='relu'))
traff_model.add(Dense(100, activation='relu'))
traff_model.add(Dense(1))

traff_model.compile(optimizer='adam', loss='mean_squared_error')
traff_model.fit(x_train, y_train, epochs=10, verbose=1)     
traff_model.evaluate(x_train, y_train)

/Users/MattPettit/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:15: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by the scale function.
  from ipykernel import kernelapp as app
/Users/MattPettit/anaconda3/lib/python3.7/site-packages/sklearn/model_selection/_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)

Epoch 1/10
33742/33742 [==============================] - 2s 48us/step - loss: 5076225.6565
Epoch 2/10
33742/33742 [==============================] - 1s 33us/step - loss: 3855069.5998
Epoch 3/10
33742/33742 [==============================] - 1s 33us/step - loss: 3831153.5309
Epoch 4/10
33742/33742 [==============================] - 1s 33us/step - loss: 3823679.1500
Epoch 5/10
33742/33742 [==============================] - 1s 32us/step - loss: 3815633.4468
Epoch 6/10
33742/33742 [==============================] - 1s 32us/step - loss: 3805887.1120
Epoch 7/10
33742/33742 [==============================] - 1s 33us/step - loss: 3802960.0913
Epoch 8/10
33742/33742 [==============================] - 1s 36us/step - loss: 3793331.6434
Epoch 9/10
33742/33742 [==============================] - 1s 34us/step - loss: 3784372.4631
Epoch 10/10
33742/33742 [==============================] - 1s 33us/step - loss: 3777935.2715
33742/33742 [==============================] - 1s 17us/step

3778692.8774672514

In [55]:
from sklearn.metrics import mean_squared_error

traff_pred = traff_model.predict(x_test)
rmse = np.sqrt(mean_squared_error(y_test, traff_pred))
rmse

1946.5810798216935

In [56]:
np.mean(y)

3259.8183553232097

In [63]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression()
reg.fit(x_train, y_train)
pred=reg.predict(x_test)
rmse = np.sqrt(mean_squared_error(y_test, pred))
np.mean(y)

3267.5414880376156

/Users/MattPettit/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in log
  """Entry point for launching an IPython kernel.

array([[        nan,         nan,         nan,         nan,  0.04074285],
       [        nan, -3.57377687,         nan,         nan,         nan],
       [        nan,         nan,         nan,         nan,         nan],
       ...,
       [        nan,  0.32628839,         nan,         nan,         nan],
       [        nan,         nan,         nan,         nan, -0.98034997],
       [        nan, -3.47220019,         nan,         nan,         nan]])

In [71]:
Traffic_DF

,holiday,temp,rain_1h,snow_1h,clouds_all,date_time,traffic_volume
0,0,288.28,0.00,0.0,40,10/2/12 9:00,5545
1,0,289.36,0.00,0.0,75,10/2/12 10:00,4516
2,0,289.58,0.00,0.0,90,10/2/12 11:00,4767
3,0,290.13,0.00,0.0,90,10/2/12 12:00,5026
4,0,291.14,0.00,0.0,75,10/2/12 13:00,4918
5,0,291.72,0.00,0.0,1,10/2/12 14:00,5181
6,0,293.17,0.00,0.0,1,10/2/12 15:00,5584
7,0,293.86,0.00,0.0,1,10/2/12 16:00,6015
8,0,294.14,0.00,0.0,20,10/2/12 17:00,5791
9,0,293.10,0.00,0.0,20,10/2/12 18:00,4770
10,0,290.97,0.00,0.0,20,10/2/12 19:00,3539
11,0,289.38,0.00,0.0,1,10/2/12 20:00,2784
12,0,288.61,0.00,0.0,1,10/2/12 21:00,2361
13,0,287.16,0.00,0.0,1,10/2/12 22:00,1529
14,0,285.45,0.00,0.0,1,10/2/12 23:00,963
15,0,284.63,0.00,0.0,1,10/3/12 0:00,506
16,0,283.47,0.00,0.0,1,10/3/12 1:00,321
17,0,281.18,0.00,0.0,1,10/3/12 2:00,273
18,0,281.09,0.00,0.0,1,10/3/12 3:00,367
19,0,279.53,0.00,0.0,1,10/3/12 4:00,814
20,0,278.62,0.00,0.0,1,10/3/12 5:00,2718
21,0,278.23,0.00,0.0,1,10/3/12 6:00,5673
22,0,278.12,0.00,0.0,1,10/3/12 8:00,6511
23,0,282.48,0.00,0.0,1,10/3/12 9:00,5471
24,0,291.97,0.00,0.0,1,10/3/12 12:00,5097
25,0,293.23,0.00,0.0,1,10/3/12 13:00,4887
26,0,294.31,0.00,0.0,1,10/3/12 14:00,5337
27,0,295.17,0.00,0.0,1,10/3/12 15:00,5692
28,0,295.13,0.00,0.0,1,10/3/12 16:00,6137
29,0,293.66,0.00,0.0,20,10/3/12 18:00,4623
...,...,...,...,...,...,...,...
48174,0,280.55,0.00,0.0,90,9/29/18 20:00,3338
48175,0,280.40,0.00,0.0,90,9/29/18 21:00,2950
48176,0,280.54,0.00,0.0,90,9/29/18 22:00,2607
48177,0,280.32,0.00,0.0,90,9/29/18 23:00,3856
48178,0,280.30,0.00,0.0,90,9/30/18 0:00,1826
48179,0,280.19,0.00,0.0,90,9/30/18 1:00,920
48180,0,280.07,0.00,0.0,90,9/30/18 2:00,696
48181,0,280.08,0.00,0.0,90,9/30/18 3:00,364
48182,0,279.88,0.00,0.0,90,9/30/18 4:00,335
48183,0,279.96,0.00,0.0,90,9/30/18 5:00,444
48184,0,280.17,0.00,0.0,90,9/30/18 6:00,802
48185,0,280.16,0.00,0.0,90,9/30/18 7:00,1175
48186,0,280.28,0.00,0.0,90,9/30/18 8:00,2002
48187,0,280.62,0.00,0.0,90,9/30/18 9:00,2882
48188,0,281.38,0.00,0.0,75,9/30/18 10:00,3701
48189,0,282.18,0.00,0.0,90,9/30/18 11:00,4049
48190,0,282.69,0.00,0.0,75,9/30/18 12:00,4429
48191,0,283.03,0.00,0.0,90,9/30/18 13:00,4547
48192,0,283.48,0.00,0.0,90,9/30/18 14:00,4380
48193,0,283.48,0.00,0.0,90,9/30/18 14:00,4380
48194,0,283.84,0.00,0.0,75,9/30/18 15:00,4302
48195,0,283.84,0.00,0.0,75,9/30/18 15:00,4302
48196,0,284.38,0.00,0.0,75,9/30/18 16:00,4283
48197,0,284.79,0.00,0.0,75,9/30/18 17:00,4132
48198,0,284.20,0.25,0.0,75,9/30/18 18:00,3947
48199,0,283.45,0.00,0.0,75,9/30/18 19:00,3543
48200,0,282.76,0.00,0.0,90,9/30/18 20:00,2781
48201,0,282.73,0.00,0.0,90,9/30/18 21:00,2159
48202,0,282.09,0.00,0.0,90,9/30/18 22:00,1450
48203,0,282.12,0.00,0.0,90,9/30/18 23:00,954

TypeError: 'int' object is not iterable